import { describe, expect, it, vi } from "vitest";
import { buildNewsletterDigest, KitAccessUnavailableError, NewsletterSynchronizer, previousCoverageMonth, publicationsForMonth, type NewsletterIssueDraft, type NewsletterIssueSource } from "../lib/content/newsletter";
import { mutateEditorialSnapshot, readActiveEditorialSnapshot } from "../lib/content/snapshot";
import type { KitDraftClient } from "../lib/content/newsletter";
import type { EditorialSnapshot, Publication, PublicationType } from "../lib/content/types";
import { articleFixture, MemoryContentStorage } from "./helpers";

function publication(type:PublicationType,slug:string,publishedAt:string):Publication{
  const base=articleFixture({notionPageId:`page-${slug}`,slug,title:slug,description:`Description for ${slug}.`,publicationType:type as "Essay",publishedAt});
  return type==="Roundup"||type==="Collection"?{...base,publicationType:type,selections:[]}: {...base,publicationType:type} as Publication;
}
function snapshot(publications:Publication[]):EditorialSnapshot{return{schemaVersion:3,publications,curatedPieces:[],contributors:[{notionPageId:"person",displayName:"vestige",slug:"vestige",bio:"Editor",role:"Editor",links:[]}],newsletterIssues:[]};}
function source(issue:NewsletterIssueDraft):NewsletterIssueSource&{prepared:ReturnType<typeof vi.fn>;failed:ReturnType<typeof vi.fn>;fallback:ReturnType<typeof vi.fn>}{const prepared=vi.fn(async()=>undefined);const failed=vi.fn(async()=>undefined);const fallback=vi.fn(async()=>"fallback-page");return{readIssue:vi.fn(async()=>issue),markPrepared:prepared,markFailed:failed,createOrUpdateFallback:fallback,prepared,failed,fallback};}

describe("monthly newsletter workflow",()=>{
  it("uses the previous New York calendar month across a UTC boundary",()=>{expect(previousCoverageMonth(new Date("2026-03-01T04:30:00Z"))).toBe("2026-01");expect(previousCoverageMonth(new Date("2026-03-01T05:30:00Z"))).toBe("2026-02");});
  it("selects by New York month and renders category order without empty sections",()=>{const pubs=[publication("Listening Guide","guide","2026-07-31T12:00:00Z"),publication("Essay","essay","2026-08-01T03:30:00Z"),publication("Roundup","roundup","2026-08-01T04:30:00Z")];expect(publicationsForMonth(pubs,"2026-07").map((item)=>item.slug)).toEqual(["guide","essay"]);const digest=buildNewsletterDigest({coverageMonth:"2026-07",subject:"July",previewText:"July work",editorNoteMarkdown:"Hello.",publications:pubs});expect(digest.html.indexOf("Essays")).toBeLessThan(digest.html.indexOf("Listening Guides"));expect(digest.html).not.toContain("Collections");expect(digest.html.match(/roundup/g)).toBeNull();});
  it("fails missing notes and empty months",()=>{expect(()=>buildNewsletterDigest({coverageMonth:"2026-07",subject:"July",previewText:"Preview",editorNoteMarkdown:"",publications:[publication("Essay","essay","2026-07-01T12:00:00Z")]})).toThrow(/editor’s note/);expect(()=>buildNewsletterDigest({coverageMonth:"2026-07",subject:"July",previewText:"Preview",editorNoteMarkdown:"Note",publications:[]})).toThrow(/No published/);});
  it("makes repeated Ready events idempotent and falls back to a copy-ready child page",async()=>{const storage=new MemoryContentStorage();await mutateEditorialSnapshot(storage,()=>snapshot([publication("Essay","essay","2026-07-02T12:00:00Z")]));const issue:NewsletterIssueDraft={notionPageId:"issue",coverageMonth:"2026-07",subject:"July",previewText:"Preview",state:"Ready",editorNoteMarkdown:"Note"};const notion=source(issue);const sync=new NewsletterSynchronizer(storage,notion);await sync.process("issue");await sync.process("issue");expect(notion.fallback).toHaveBeenCalledTimes(1);expect(notion.prepared).toHaveBeenCalledTimes(2);});
  it("creates an unscheduled Kit draft, freezes Sent archives, and ignores repeated Sent events",async()=>{const storage=new MemoryContentStorage();await mutateEditorialSnapshot(storage,()=>snapshot([publication("Roundup","roundup","2026-07-05T12:00:00Z")]));const issue:NewsletterIssueDraft={notionPageId:"issue",coverageMonth:"2026-07",subject:"July",previewText:"Preview",state:"Ready",editorNoteMarkdown:"Note"};const notion=source(issue);const kit:KitDraftClient={createOrUpdateDraft:vi.fn(async()=>"broadcast-1")};const sync=new NewsletterSynchronizer(storage,notion,kit,()=>new Date("2026-08-03T12:00:00Z"));await sync.process("issue");issue.state="Sent";issue.generatedContentHash=notion.prepared.mock.calls[0][1].contentHash;await sync.process("issue");const writesAfterFirstSent=storage.writes.length;await sync.process("issue");const archive=(await readActiveEditorialSnapshot(storage)).editorial.newsletterIssues;expect(archive).toHaveLength(1);expect(storage.writes).toHaveLength(writesAfterFirstSent);expect(archive[0]).toMatchObject({coverageMonth:"2026-07",publications:["roundup"],contentHash:issue.generatedContentHash});expect(kit.createOrUpdateDraft).toHaveBeenCalledTimes(1);});
  it("records a Kit failure without publishing an archive",async()=>{const storage=new MemoryContentStorage();await mutateEditorialSnapshot(storage,()=>snapshot([publication("Essay","essay","2026-07-02T12:00:00Z")]));const issue:NewsletterIssueDraft={notionPageId:"issue",coverageMonth:"2026-07",subject:"July",previewText:"Preview",state:"Ready",editorNoteMarkdown:"Note"};const notion=source(issue);const kit:KitDraftClient={createOrUpdateDraft:vi.fn(async()=>{throw new Error("Kit unavailable")})};await expect(new NewsletterSynchronizer(storage,notion,kit).process("issue")).rejects.toThrow("Kit unavailable");expect(notion.failed).toHaveBeenCalledWith("issue","Kit unavailable");expect((await readActiveEditorialSnapshot(storage)).editorial.newsletterIssues).toEqual([]);});
  it("uses the Notion fallback when Kit draft access is unavailable on the plan",async()=>{const storage=new MemoryContentStorage();await mutateEditorialSnapshot(storage,()=>snapshot([publication("Essay","essay","2026-07-02T12:00:00Z")]));const issue:NewsletterIssueDraft={notionPageId:"issue",coverageMonth:"2026-07",subject:"July",previewText:"Preview",state:"Ready",editorNoteMarkdown:"Note"};const notion=source(issue);const kit:KitDraftClient={createOrUpdateDraft:vi.fn(async()=>{throw new KitAccessUnavailableError()})};await new NewsletterSynchronizer(storage,notion,kit).process("issue");expect(notion.fallback).toHaveBeenCalledOnce();expect(notion.failed).not.toHaveBeenCalled();});
});
