import { describe,expect,it } from "vitest";
import { validateEditorialSnapshot } from "../lib/content/snapshot";
import { articleFixture } from "./helpers";

describe("schema v3 compatibility",()=>{
  it("normalizes v1 articles as Essays or Listening Guides",()=>{const result=validateEditorialSnapshot({schemaVersion:1,articles:[{...articleFixture(),author:"vestige",contentType:"guide",tags:["rap"],publicationType:undefined,contributor:undefined,topics:undefined}]});expect(result.schemaVersion).toBe(3);expect(result.publications[0]).toMatchObject({publicationType:"Listening Guide",contributor:"vestige",topics:["rap"]});});
  it("normalizes v2 originals and Collections",()=>{const legacy={...articleFixture(),author:"vestige",contentType:"Essay",tags:["rap"],publicationType:undefined,contributor:undefined,topics:undefined};const result=validateEditorialSnapshot({schemaVersion:2,originals:[legacy],curatedLinks:[{id:"outside",title:"Outside",canonicalUrl:"https://example.com/outside",writer:"Writer",publication:"Source",publishedAt:"2025-01-01",editorialNote:"Note",topics:["rap"]}],collections:[{slug:"legacy-collection",title:"Legacy",description:"Description",introduction:"Introduction",publishedAt:"2026-01-01",updatedAt:"2026-01-01",topics:["rap"],selections:[{kind:"original",slug:"first-path"},{kind:"curated",slug:"outside"}]}],contributors:[{notionPageId:"person",displayName:"vestige",slug:"vestige",bio:"Editor",role:"Editor",links:[]}]});expect(result.publications.map((item)=>item.publicationType)).toEqual(expect.arrayContaining(["Collection","Essay"]));expect(result.curatedPieces[0]).toMatchObject({sourcePublication:"Source",annotation:"Note"});});
  it("rejects canonical URL duplicates after normalization",()=>{const piece={notionPageId:"one",id:"one",title:"One",canonicalUrl:"https://EXAMPLE.com/story/",writer:"Writer",sourcePublication:"Source",originalDate:"2026-01-01",topics:[],annotation:"Note"};expect(()=>validateEditorialSnapshot({schemaVersion:3,publications:[],curatedPieces:[piece,{...piece,notionPageId:"two",id:"two",canonicalUrl:"https://example.com/story"}],contributors:[],newsletterIssues:[]})).toThrow("The active content snapshot is invalid.");});
});
